### ISSUE TITLE
Contract tests checklist

### ISSUE THREAD

**Issue by whalelephant** [nymlab/vectis#103]
### dao_tunnel
- [x] executeMsg 
- [x] queries
- [x] ibc open
- [x] ibc close
- [x] ibc connect
- [x] ibc receive
    - [x] package parsing
    - [x] remote tunnel actions
         - [x] mint govec
         - [x] Govec actions
         - [x] ~Stake actions (Needs to be in multitest)~
         - [x] Proposal actions
- [x] ibc ack
- [x] ibc timeout

### remote_tunnel
- [x] executeMsg 
- [x] queries
- [x] ibc open
- [x] ibc close
- [x] ibc connect
- [x] ibc receive
    - [x] package parsing
    - [x] dao tunnel actions
         - [x] daoconfig
         - [x] chainconfig
         - [x] factory instantiate
         - [x] approve ibc modules
         - [x] dispatch other actions
- [x] ibc ack
- [x] ibc timeout

### Govec
- [x] executeMsg
- [x] queryMsg

### Proxy
- [x] executeMsg
- [x] queryMsg

### Factory remote
- [x] executeMsg (excludes multicontracts, i.e. create wallet, mint govec, purge claims etc)
- [x] queryMsg

### Factory dao-chain
- [x] executeMsg (excludes multicontracts, i.e. create wallet, mint govec, purge claims etc)
- [x] queryMsg

### Dao chain
- [x] create wallet
- [x] mint govec
- [x] propose actions
- [x] stake actions
- [x] govec actions
- [x] migrate proxy
- [x] new proxy multisig

### Remote chain
- [x] create wallet

- [x] migrate proxy
- [x] new proxy multisig

_Moving the below to the typescript tests_
- migrate factory
- migrate govec
-  migrate dao-tunnel
- migrate factory
- migrate remote-tunnel
- execute daotunnelMsg (staking / unstaking native)
- mint govec
- propose actions
- stake actions
- govec actions

**Comment by j0nl1** [comment]
## Client Side Tests

### DAO 

- [ ] Deployer account should not have any token or being admin of the contract.
- [ ] All contracts should have DAO as admin.
- [ ] DAO should have 4 proposal executed.
- [ ] DAO should contain the right information for marketing.
- [ ] DAO should be the only one authorized for communicate with dao_tunnel.
- [ ] DAO should be able to add approved controllers in dao_tunnel.
- [ ] DAO should be able to remove approved controllers in dao_tunnel.
- [ ] DAO should be able to update host factory configuration.
     - [ ] Code ID
     - [ ] Wallet Fee
     - [ ] Govec Addr
     - [ ] DAO Addr
- [ ] DAO should be able to dispatch messages to remote_tunnel through dao_tunnel.
     - [ ] Update DAO Config,
     - [ ] Update Chain Config,
     - [ ] Instantiate Factory.
     - [ ] Update IBC Transfer Receiver Channel.
     - [ ] Dispatch action that are not related with remote_tunnel.
     - [ ] Update Remote Factory
         - [ ] Code ID
         - [ ] Wallet Fee
         - [ ] Govec Addr
         - [ ] DAO Addr

### Users
- [ ] Factory should be able to instantiate a proxy wallet.
- [ ] Factory should be able to migrate a proxy wallet.
- [ ] Factory should allow to claim govec to new proxy wallets.
- [ ] Proxy should be able to execute transactions.
- [ ] Proxy should let user change their label.
- [ ] Proxy should accept request for updating guardians.
- [ ] Proxy should update guardians, if the guardian request passed the waiting time.
- [ ] Proxy should be able to add or remove a relayer.
- [ ] Remote tunnel should allow govec operations to proxy wallets.
- [ ] Remote tunnel should allow stake actions to proxy wallets.
- [ ] Remote tunnel should allow proposal actions to proxy wallets.

### Guardians
> No multisig
- [ ] Proxy should let guardians to rotate users key
- [ ] Proxy should let guardians to freeze and unfreeze the contract.
> Multisig
- [ ] Guardians can create proposals for freeze/unfreeze or rotate user key.
- [ ] Guardians can execute proposals after pass the threshold.

### Relayers
TBD


- [ ] Anyone should be able to purge expired claims
